openapi: 3.0.0
info:
  title: Mywaypay
  version: '1.0'
  description: This document references ways in which one can use mywaypay services to intergrate invoice and payment notifications to their system with minimal effort
  contact:
    name: Imani Labs
    url: imanilabs.com
    email: isaac@imanilabs.com
  license:
    name: MIT
    url: none
  termsOfService: none
servers:
  - description: Sandbox
    url: 'https://sandbox.mywaypay.io'
  - url: 'https://web.mywaypay.io'
    description: Live server
paths:
  /api-token:
    post:
      summary: Retrieve Access Token
      tags:
        - authentication
        - auth
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  token_type:
                    type: string
                  expires_in:
                    type: number
                  access_token:
                    type: string
              examples:
                auth response:
                  value:
                    token_type: Bearer
                    expires_in: 86400
                    access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxMyIsImp0aSI6ImFkZmM3MWQ0NTkyMjJhODkxYjM3OGZlYzZhYTU2NzU4YzlmNjQyODgxMTMyZWYyMWMzNGFlN2UwMzJiY2Q5MjhhNzNjYzEzYWIzZGYxY2RiIiwiaWF0IjoxNjAwMzIyNzI1LCJuYmYiOjE2MDAzMjI3MjUsImV4cCI6MTYwMDQwOTEyNSwic3ViIjoiIiwic2NvcGVzIjpbXX0.XB0fUhuywWKj6RZRZ6yZsbPs0lpBl9pCLUr0ie4LkC1ApsED1AUkig0IheXxyTYORp3fCc9iipIfszCDt711xBpFaWzE5sDjiQoUG-XVa6NZvJv-XVOTpXl8PewuD1gIx2wWKzvRYg99Jbb93Szia3_8_ItlRQZH-Gac0dg-dZXhNtZwmGM1WBGiJHQD7G6EIgxPIZoiSYbg3mUqlM2cdp9JxirIRhJLjk1M52Vo2UMgISYTvzH2WBy-NZh7imCyKroLfkQRmrS_Z0jnHea7CwJpLP8ydJ5AOvChpd1-hDVSOAr2DeUn0DkgJqqRR8GEIolYyCyVbW7H9Z_M6zW0NKbIFSVOgpCE9AtZ1DxefudeRqg8XfB_hYoqJox7Q5Ox_oksx4fyRWUyX3eWDSCcdHVdbO5ZxYOqu6NIXjktTuqOy6l5nCpvl-zOcwtumduzSEF4Ln9ODMHEt06hl2hZldC6h58ovR1ZkF0oOCROLa82xzlykfpqZluKdBQR9Qjs2QSQNCYWdiSh8KTmjf5HTR7uFu2xoPRv7JKZNgTo80HI4htOhVrvVA34B_m6IDEIgRuUIwZPaYVsoB0KTs-HCcyt7ObUfTJ9ql6mUi3TSdMJzeL290NHGsBdHiZolbtdSrbd8bcDspCLkspUVAZ3EPlcb3KCGXPB3NZFxi4X0HI
      operationId: Authenticate
      description: Retrieve the access token by providing the client secret and client key.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                client_key:
                  type: string
                client_secret:
                  type: string
          application/xml:
            schema:
              type: object
              properties:
                client_key:
                  type: string
                client_secret:
                  type: string
              required:
                - client_key
          multipart/form-data:
            schema:
              description: ''
              type: object
              properties:
                client_secret:
                  type: string
                  minLength: 1
                client_key:
                  type: string
                  minLength: 1
              required:
                - client_secret
                - client_key
        description: ''
  /api/v1/stk:
    post:
      summary: MPesa Express (STK Push)
      tags:
        - stk
        - Stk Initialization
        - stk push
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  MerchantRequestID:
                    type: string
                  CheckoutRequestID:
                    type: string
                  ResponseCode:
                    type: string
                  ResponseDescription:
                    type: string
                  CustomerMessage:
                    type: string
      operationId: post-api-v1-stk
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                phone:
                  type: string
                reference:
                  type: string
                description:
                  type: string
                type:
                  type: string
                  enum:
                    - api
                callback:
                  type: string
                account:
                  type: string
              required:
                - amount
                - phone
                - reference
                - description
                - type
                - callback
                - account
        description: ''
  api/v1/invoice/:
    get:
      summary: get all invoices
      tags:
        - invoices
        - invoice
      responses: {}
      operationId: get-api-v1-invoice
    post:
      summary: save an invoice
      tags:
        - invoices
        - invoice
      responses: {}
      operationId: post-api-v1-invoice
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      units:
                        type: string
                      discountByPercent:
                        type: string
                      tax:
                        type: string
                      discount:
                        type: string
                      taxByPercent:
                        type: string
                      quantity:
                        type: string
                      unit_price:
                        type: string
                    required:
                      - name
                      - quantity
                      - unit_price
                group:
                  type: number
                  description: |
                    customer group id
                customers:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                send_invoice:
                  type: boolean
              required:
                - items
    delete:
      summary: delete an invoice
      tags:
        - invoices
        - invoice
      responses: {}
      operationId: delete-api-v1-invoice
    parameters:
      - schema:
          type: number
        name: id
        in: path
        description: ''
  /api/v1/quotation:
    get:
      summary: Retrieve Quotations
      tags:
        - Quotation
        - Quotations
      responses: {}
      operationId: get-api-v1-quotation
      description: Retrieve a collection of quotations from the authenticated account.
    post:
      summary: Save a Quotation
      responses: {}
      operationId: post-api-v1-quotation
      description: Create a new quotation.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      units:
                        type: string
                      discountByPercent:
                        type: string
                      tax:
                        type: string
                      discount:
                        type: string
                      taxByPercent:
                        type: string
                      quantity:
                        type: string
                      unit_price:
                        type: string
                    required:
                      - name
                      - quantity
                      - unit_price
                group:
                  type: number
                  description: |
                    customer group id
                customers:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
              required:
                - items
        description: ''
      tags:
        - quotation
        - quotations
    delete:
      summary: Delete a Quotation
      responses: {}
      operationId: delete-api-v1-quotation
      tags:
        - quotation
        - quotations
  '/api/v1/invoice/send/{id}':
    post:
      summary: Send invoice to customer
      tags:
        - send invoice
      responses: {}
      operationId: post-api-v1-invoice-send
      parameters: []
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Invoice id
  /api/v1/callback:
    get:
      summary: Show the registered callback
      tags:
        - callbacks
        - callback
      responses: {}
      operationId: get-api-v1-callback
    post:
      summary: Post a new callback
      tags:
        - callbacks
        - callback
      responses: {}
      operationId: post-api-v1-callback
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payment:
                  type: string
                  format: uri
                invoice:
                  type: string
                  format: uri
      description: Create a new callback or update an existing one
    delete:
      summary: Remove a callback
      tags:
        - callbacks
        - callback
      responses: {}
      operationId: delete-api-v1-callback
    parameters: []
  /api/v1/sms:
    get:
      summary: Retrieve list of messages
      tags:
        - messaging
      responses: {}
      operationId: get-api-v1-sms
      parameters:
        - schema:
            type: string
          in: header
          name: Accept
          description: application/json
    post:
      summary: Send a new set of messages
      tags:
        - messaging
      responses: {}
      operationId: post-api-v1-sms
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                phone:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      value:
                        type: number
                        description: Phone Numbers
                        minimum: 9
                        maximum: 10
                        example: 710012542
                        exclusiveMinimum: true
                        exclusiveMaximum: true
                    required:
                      - value
                message:
                  type: string
                  minLength: 1
              required:
                - phone
                - message
  /api/v1/withdraw:
    post:
      summary: Withdraw from Wallet
      tags: []
      responses: {}
      operationId: post-api-v1-withdraw
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                wallet_id:
                  type: number
                channel:
                  type: string
                  minLength: 1
                amount:
                  type: number
                account:
                  type: string
                  minLength: 1
                password:
                  type: string
                  minLength: 1
              required:
                - wallet_id
                - channel
                - amount
                - account
                - password
          application/xml:
            schema:
              type: object
              properties: {}
  /api/v1/wallets:
    get:
      summary: List all the user's wallets
      tags:
        - Wallets
      responses: {}
      operationId: get-api-v1-wallets
    post:
      summary: ''
      operationId: post-api-v1-wallets
      responses:
        '200':
          description: OK
      description: 'Create wallet '
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                slug:
                  type: string
                  minLength: 1
                description:
                  type: string
                  minLength: 1
              required:
                - name
                - slug
                - description
  /api/v1/group:
    get:
      summary: List customer groups
      tags:
        - Customer group
        - billing group
      responses: {}
      operationId: get-api-v1-groups
    post:
      summary: Create a new customer group
      tags:
        - Customer group
        - billing group
      responses: {}
      operationId: post-api-v1-groups
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customers:
                  type: array
                  items:
                    type: object
                    properties:
                      email:
                        type: string
                      name:
                        type: string
                      phone_number:
                        type:
                          - number
                          - string
                    required:
                      - email
                      - name
                name:
                  type: string
                description:
                  type: string
                '':
                  type: string
              required:
                - customers
                - name
                - description
    parameters: []
  '/pgw/payment/checkout/{context}':
    get:
      summary: Checkout
      tags: []
      responses: {}
      operationId: get-pgw-payment-checkout-default
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: string
                order_no:
                  type: string
                reference:
                  type: string
                merchant_id:
                  type: number
                email:
                  type: string
                currency_code:
                  type: string
                redirect_url:
                  type: string
                callback_url:
                  type: string
      description: |-
        Context to be used is : default

        Confirm with our support first to get the correct context
      parameters: []
    post:
      summary: Checkout
      tags: []
      responses: {}
      operationId: post-pgw-payment-checkout-default
      description: |-
        Context to be used is : default

        Confirm with our support first to get the correct context


        Other contexts will be provided
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                amount:
                  type: string
                  minLength: 1
                order_no:
                  type: string
                  minLength: 1
                reference:
                  type: string
                  minLength: 1
                merchant_id:
                  type: string
                  minLength: 1
                email:
                  type: string
                  minLength: 1
                currency_code:
                  type: string
                  minLength: 1
                redirect_url:
                  type: string
                  minLength: 1
                callback_url:
                  type: string
                  minLength: 1
              required:
                - amount
                - order_no
                - reference
                - merchant_id
                - email
                - currency_code
                - redirect_url
                - callback_url
              x-examples:
                example-1:
                  amount: string
                  order_no: string
                  reference: string
                  merchant_id: string
                  email: string
                  currency_code: string
                  redirect_url: string
                  callback_url: string
    parameters:
      - schema:
          type: string
        name: context
        in: path
        required: true
components:
  schemas: {}
  securitySchemes: {}
tags:
  - name: invoices
  - name: quotation
  - name: quotations
