openapi: 3.0.0
info:
  title: Mywaypay
  version: '1.0'
  description: This document references ways in which one can use mywaypay services to intergrate invoice and payment notifications to their system with minimal effort
  contact:
    name: Imani Labs
    url: imanilabs.com
    email: isaac@imanilabs.com
  license:
    name: MIT
    url: none
  termsOfService: none
servers:
  - description: Sandbox
    url: 'https://test.mywaypay.io'
paths:
  /api-token:
    post:
      summary: get access token
      tags:
        - authentication
        - auth
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  token_type:
                    type: string
                  expires_in:
                    type: number
                  access_token:
                    type: string
              examples:
                auth response:
                  value:
                    token_type: Bearer
                    expires_in: 86400
                    access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxMyIsImp0aSI6ImFkZmM3MWQ0NTkyMjJhODkxYjM3OGZlYzZhYTU2NzU4YzlmNjQyODgxMTMyZWYyMWMzNGFlN2UwMzJiY2Q5MjhhNzNjYzEzYWIzZGYxY2RiIiwiaWF0IjoxNjAwMzIyNzI1LCJuYmYiOjE2MDAzMjI3MjUsImV4cCI6MTYwMDQwOTEyNSwic3ViIjoiIiwic2NvcGVzIjpbXX0.XB0fUhuywWKj6RZRZ6yZsbPs0lpBl9pCLUr0ie4LkC1ApsED1AUkig0IheXxyTYORp3fCc9iipIfszCDt711xBpFaWzE5sDjiQoUG-XVa6NZvJv-XVOTpXl8PewuD1gIx2wWKzvRYg99Jbb93Szia3_8_ItlRQZH-Gac0dg-dZXhNtZwmGM1WBGiJHQD7G6EIgxPIZoiSYbg3mUqlM2cdp9JxirIRhJLjk1M52Vo2UMgISYTvzH2WBy-NZh7imCyKroLfkQRmrS_Z0jnHea7CwJpLP8ydJ5AOvChpd1-hDVSOAr2DeUn0DkgJqqRR8GEIolYyCyVbW7H9Z_M6zW0NKbIFSVOgpCE9AtZ1DxefudeRqg8XfB_hYoqJox7Q5Ox_oksx4fyRWUyX3eWDSCcdHVdbO5ZxYOqu6NIXjktTuqOy6l5nCpvl-zOcwtumduzSEF4Ln9ODMHEt06hl2hZldC6h58ovR1ZkF0oOCROLa82xzlykfpqZluKdBQR9Qjs2QSQNCYWdiSh8KTmjf5HTR7uFu2xoPRv7JKZNgTo80HI4htOhVrvVA34B_m6IDEIgRuUIwZPaYVsoB0KTs-HCcyt7ObUfTJ9ql6mUi3TSdMJzeL290NHGsBdHiZolbtdSrbd8bcDspCLkspUVAZ3EPlcb3KCGXPB3NZFxi4X0HI
      operationId: post-api-token
      description: Exchange the client-secret and client-key for an access token.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
          application/xml:
            schema:
              type: object
              properties:
                client_key:
                  type: string
                client_secret:
                  type: string
              required:
                - client_key
        description: ''
  /api/v1/stk:
    post:
      summary: Stk push
      tags:
        - stk
        - Stk Initialization
        - stk push
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  MerchantRequestID:
                    type: string
                  CheckoutRequestID:
                    type: string
                  ResponseCode:
                    type: string
                  ResponseDescription:
                    type: string
                  CustomerMessage:
                    type: string
      operationId: post-api-v1-stk
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                phone:
                  type: string
                reference:
                  type: string
                description:
                  type: string
                type:
                  type: string
                  enum:
                    - api
              required:
                - amount
                - phone
                - reference
                - description
                - type
        description: ''
  api/v1/invoice/:
    get:
      summary: get all invoices
      tags:
        - invoices
        - invoice
      responses: {}
      operationId: get-api-v1-invoice
    post:
      summary: save an invoice
      tags:
        - invoices
        - invoice
      responses: {}
      operationId: post-api-v1-invoice
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      units:
                        type: string
                      discountByPercent:
                        type: string
                      tax:
                        type: string
                      discount:
                        type: string
                      taxByPercent:
                        type: string
                      quantity:
                        type: string
                      unit_price:
                        type: string
                    required:
                      - name
                      - quantity
                      - unit_price
                group:
                  type: number
                  description: |
                    customer group id
                customers:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
              required:
                - items
    delete:
      summary: delete an invoice
      tags:
        - invoices
        - invoice
      responses: {}
      operationId: delete-api-v1-invoice
    parameters:
      - schema:
          type: number
        name: id
        in: path
        description: ''
  /api/v1/quotation:
    get:
      summary: list quotations
      tags:
        - quotation
        - quotations
      responses: {}
      operationId: get-api-v1-quotation
    post:
      summary: save an invoice
      tags:
        - invoices
        - invoice
      responses: {}
      operationId: post-api-v1-quotation
      description: Submit a quotation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      units:
                        type: string
                      discountByPercent:
                        type: string
                      tax:
                        type: string
                      discount:
                        type: string
                      taxByPercent:
                        type: string
                      quantity:
                        type: string
                      unit_price:
                        type: string
                    required:
                      - name
                      - quantity
                      - unit_price
                group:
                  type: number
                  description: |
                    customer group id
                customers:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
              required:
                - items
        description: ''
    delete:
      summary: delete quotation
      tags:
        - quotation
        - quotations
      responses: {}
      operationId: delete-api-v1-quotation
components:
  schemas: {}
  securitySchemes:
    Authentication:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://web.mywaypay.io/api-token'
          scopes: {}
          refreshUrl: 'https://web.mywaypay.io/oauth/refresh'
      description: ''
security:
  - Authentication: []
